export const ERROR = 'ERROR';
export const LOADING = 'LOADING';
export const SET_SEARCH = 'SET_SEARCH';
export const SET_SEARCH_DATA = 'SET_SEARCH_DATA';

export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS';
export const ADDING_POST = 'ADDING_POST';
export const REMOVING_POST = 'REMOVING_POST';
export const REMOVE_POST_SUCCESS = 'REMOVE_POST_SUCCESS';
export const EDITING_POST = 'EDITING_POST';
export const EDIT_POST_SUCCESS = 'EDIT_POST_SUCCESS';